### ISSUE TITLE
Automatic recording for SNR Test 

### ISSUE THREAD

**Issue by mcfrancho1** [sebsilas/musicassessr#1]
The SNR test page does not automatically check the background noise. The record and stop buttons should be removed.

**Comment by sebsilas** [comment]
To be clear: this issue was about recording not stopping automatically after the SNR test, something that was discarded with the introduction of some new features, but should have remained supported.

This as the other issue you mentioned (the bug regarding SNR testing not working locally) have been fixed on the `api-mode` branch 08e6785f3523196f9f45ec21eeb76d4c207ebaff, so you will have to install from there for now. It will probably be a few weeks before `api-mode` is merged into master.
